### PR TITLE
feat(build): split build steps into scripts/

### PR DESCRIPTION
**Pull request by orthros**
Makes build scripts more testable with `shellcheck`

### CODE REVIEW

**Comment by orthros** [comment]
Fixes #87

**Comment by bcoe** [comment]
If we can get tests passing 👍 looks like a great refactor to me.

**Comment by orthros** [comment]
I'll try re-merging from master. Strange that they are all failing; I did not change any of the js files :thinking:

**Comment by orthros** [comment]
Strangely enough this is a problem with master. I'll investigate

**Comment by orthros** [comment]
This will be fixed when #89 is merged

**Pull request merged**
