### PR TITLE
feat: Adding DEE Asset labels

### PR DESCRIPTION
**Pull request by rsamborski**
Adding DEE asset labels to support auto-tagging efforts. See go/dee-auto-tagging for more information.

### CODE REVIEW

**Review by chingor13 — CHANGES_REQUESTED** [review]
This will add labels to _every_ repository that this bot is installed on. These do not feel like they belong on every repository.

If this is for use with auto-label, we could add a feature to that bot that adds necessary labels if they exist in the auto-label config.

**Comment by rsamborski** [comment]
> This will add labels to _every_ repository that this bot is installed on. These do not feel like they belong on every repository.
> 
> If this is for use with auto-label, we could add a feature to that bot that adds necessary labels if they exist in the auto-label config.

To clarify we are going to use these labels without auto-label too. There might be situations in which the label is added manually by a DEE member and then processed by internal tagging tool running on Buganizer mirrored issues (see [go/dee-ops-live-docs](https://goto.google.com/dee-ops-live-docs) and [dee.yaml](http://shortn/_Kr3xZmqTRf)).

I could manually add these labels to DEE owned repositories, but if you look into the dee.yaml config file you will notice that we already monitor quite a few of them. Manually making sure they all have proper labels is a quite cumbersome task, so I naturally leaned towards the use of this bot.

**Comment by rsamborski** [comment]
Thanks for the suggestion. I have reported a feature request under #5040. Closing this PR for now.

**Comment by SurferJeffAtGoogle** [comment]
> This will add labels to _every_ repository that this bot is installed on. These do not feel like they belong on every repository.

@chingor13  I agree that these labels will only apply to a small number of repositories. What would be the costs associated with accepting this pull request?

**Comment by chingor13** [comment]
> What would be the costs associated with accepting this pull request?

These labels could annoy repository maintainers that don't use these labels. The maintainers won't be able to remove the labels (they will be readded the next night).

This bot is installed on ~800 googleapis and 25 GoogleCloudPlatform repos and is only needed by a handful of repos.

**Pull request closed without merging**
