### PR TITLE
chore(owl-bot): add updated cross-spawn dependency

### PR DESCRIPTION
**Pull request by diegomarquezp**
Fixes the cross-spawn [CVE](https://github.com/advisories/GHSA-3xgq-45jj-v275) by directly adding it to package + package-lock.

### CODE REVIEW

**Review by chingor13 — COMMENTED** [review]
I think this dependency was already updated in #5562

**Comment by diegomarquezp** [comment]
> I think this dependency was already updated in #5562

The lock file still left a few versions under `7.0.5`
https://github.com/googleapis/repo-automation-bots/blob/c64c6a64491ab48d12c3d4391a0d5f1aa806eb4e/packages/owl-bot/package-lock.json#L3486

Not sure if it downloads one copy of the dependency per parent dependency?

**Comment by chingor13** [comment]
> > I think this dependency was already updated in #5562
> 
> @chingor13 The lock file still left a few versions under `7.0.5`
> 
> https://github.com/googleapis/repo-automation-bots/blob/c64c6a64491ab48d12c3d4391a0d5f1aa806eb4e/packages/owl-bot/package-lock.json#L3486
> 
> Not sure if it downloads one copy of the dependency per parent dependency?

This is the declared dependency from a direct dependency, not the version resolved.

**Pull request closed without merging**
