### PR TITLE
build(owl-bot): refactor frontend deployment

### PR DESCRIPTION
**Pull request by tmatsuo**
so that we can deploy the backend cloud run with lower risk.

### CODE REVIEW

**Review by chingor13 — COMMENTED** [review]
The frontend and backend can run the same docker image

**Comment by tmatsuo** [comment]
> The frontend and backend can run the same docker image

Yeah I know, but separating allows us to deploy the backend cloud run with minimal risk.

**Comment by tmatsuo** [comment]
Also, the owlbot bootstrap needs to fetch secrets which is a performance penalty for cold start.

**Review by chingor13 — APPROVED** [review]
Currently the docker image is serving the frontend so, this is just renaming the image in case we want different images between the frontend and backend?

**Comment by tmatsuo** [comment]
@chingor13 Yes, I'll add backend docker image in the next PR.

**Pull request merged**
