### PR TITLE
feat: flag tells owl-bot to squash first post-processor update

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
As requested by .NET maintainers.  They don't want to see all the
changes to the staging directory in their git history.

Here's how it works:
1. Owl Bot copies code from googleapis-gen and creates pull request in
   client library repo.  The pull request body contains a Copy-Tag.
2. Owl Bot runs the post processor as usual on the pull request.
3. Owl Bot examines the Copy-Tag in the most recent commit only.
   Most commits will not have a Copy-Tag, in which case jump to step 6.
4. Owl Bot inspects the .OwlBot.yaml file specified by the Copy-Tag.
5. If the .OwlBot.yaml has `squash: true`, then Owl Bot squashes the
   changes introduced by the post processor.
6. Otherwise, Owl Bot adds a new commit as usual.
7. Owl Bot pushes the changes back to the pull request.

To avoid a 3-minute window of brokenness, this pull request does not
contain the necessary changes to update-pr.yaml.
Another pull request will replace the last 4 commands in update-pr.yaml
with a call to commit-post-processor-update.

### CODE REVIEW

**Comment by SurferJeffAtGoogle** [comment]
cc @jskeet @amanda-tarafa

**Comment by jskeet** [comment]
Thank you! Will try to understand the change in more detail tomorrow just for the sake of getting a better understanding of OwlBot in general, but I'm definitely not competent to actually review :)

**Comment by SurferJeffAtGoogle** [comment]
cc @bcoe

**Review by tmatsuo — APPROVED** [review]

**Comment by jskeet** [comment]
Hooray! Thanks so much for this.

Do I need to wait for an OwlBot release of some description to happen before using it, or does it just become available immediately now that it's merged?

**Comment by SurferJeffAtGoogle** [comment]
You can immediately set the `squash: true` flag in your .OwlBot.yaml files, but they won't take effect until I merge the next PR, which probably won't happen 'til Monday since I'm taking an afternoon vacation and don't work Friday.

**Comment by jskeet** [comment]
Cracking - thanks! Enjoy the mini-vacation time :)

**Pull request merged**
